language: csharp
sudo: false
env:
  global:
  - TARGET=Rebuild
  matrix:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release
addons:
  apt:
    packages:
    - nuget
    - nunit-console
    - make
mono:
 - alpha
 - beta
 - weekly
 - latest
 - 4.4.0
 - 4.2.3
 # 4.2.1 is available on debian stretch and ubuntu xenial
 - 4.2.1
 # 3.2.8 is available on debian jessie and ubuntu trusty
 - 3.2.8
matrix:
 allow_failures:
  - mono: weekly
  - mono: alpha
  - mono: 3.2.8
install:
  - make packages
script:
  - make test
