language: csharp
sudo: false
addons:
  apt:
    packages:
    - nuget
    - nunit-console
mono:
 - alpha
 - beta
 - weekly
 - latest
matrix:
 allow_failures:
  - mono: weekly
  - mono: alpha
install:
  - nuget restore
script:
  - xbuild /tv:4.0 /p:Configuration=Debug /t:Rebuild
  - nunit-console com.opentrigger.distributor/tests/bin/Debug/*.dll