language: csharp
sudo: false
env:
  global:
  - TARGET=Rebuild
  matrix:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release
addons:
  apt:
    packages:
    - nuget
    - nunit-console
    - make
    - checkinstall
mono:
 - alpha
 - beta
 - weekly
 - latest
matrix:
 allow_failures:
  - mono: weekly
  - mono: alpha
install:
  - make packages
script:
  - make test
  - make deb
