language: csharp
sudo: false
env:
  global:
  - TARGET=Rebuild
  matrix:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release
addons:
  apt:
    packages:
    - nuget
    - nunit-console
    - make
    - env
mono:
 - alpha
 - beta
 # mono 4.5.x - mcs seems to freeze, disabled for now
 # - weekly
 # 4.4.2 important target - stable release at time of development (4.4.2 only available as :latest in travis for some reason)
 - latest
 # 4.2.1 important target - is available on debian stretch and ubuntu xenial
 - 4.2.1
 # 3.2.8 best-affort target - is available on debian jessie and ubuntu trusty (but no nuget)
matrix:
 allow_failures:
  - mono: weekly
  - mono: alpha
install:
  - make packages
script:
  - make test
  - make deb
deploy:
  provider: script
  script: make publish
  on:
    branch: master
    mono: 4.2.1
    condition: $CONFIGURATION = Release
