language: csharp
sudo: false
env:
  global:
  - TARGET=Rebuild
  matrix:
  - CONFIGURATION=Release
  - CONFIGURATION=Debug
addons:
  apt:
    packages:
    - nuget
    - nunit-console
    - make
mono:
 - alpha
 - beta
 - weekly
 # 4.4.2 important target - stable release at time of development (4.4.2 only available as :latest in travis for some reason)
 - latest 
 - 4.4.1
 - 4.4.0
 - 4.2.3
 # 4.2.1 important target - is available on debian stretch and ubuntu xenial
 - 4.2.1
 # 3.2.8 no nuget - is available on debian jessie and ubuntu trusty 
matrix:
 allow_failures:
  - mono: weekly
  - mono: alpha
  - mono: beta
install:
  - make packages
script:
  - make test
  - make deb
deploy:
  provider: script
  script: make publish
  skip_cleanup: true
  on:
    branch: master
    condition: '( $CONFIGURATION = Release ) && ( `mono --version | grep -q "compiler version 4.2.1" && echo 1`)'
