language: csharp
sudo: false
git:
  depth: 1024
env:
  global:
  - TARGET=Rebuild
  matrix:
  - CONFIGURATION=Release
  - CONFIGURATION=Debug
addons:
  apt:
    packages:
    - nuget
    - nunit-console
    - make
mono:
 # alpha
 # beta
 # weekly
 - latest
 - 4.8.1
 - 4.6.2
 # 4.4.2 stable release when development started
 - 4.4.2 
 # 4.4.1
 # 4.4.0
 # 4.2.3
 # 4.2.1 important target - is available on debian stretch and ubuntu xenial
 - 4.2.1
matrix:
 allow_failures:
  - mono: weekly
  - mono: alpha
  - mono: beta
  - mono: latest
install:
  - make packages
script:
  - make test
  - make deb
deploy:
  provider: script
  script: make publish && cd quickinstall && ./publish.sh
  skip_cleanup: true
  on:
    branch: master
    condition: '( $CONFIGURATION = Release ) && ( `mono --version | grep -q "compiler version 4.6.2" && echo 1`)'
