.\" Manpage for nuseradd.
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 8 "" "__VERSION__" "distributord man page"
.SH NAME
distributord \- start new opentrigger-distributor
.SH SYNOPSIS
distributird \-c </path/to/config.json>
.SH DESCRIPTION
Datacollection tool for CoAP/MQTT which distributes Events.
Part of the opentrigger platform.
.SH OPTIONS
\-c <file> specify config file

\-v        increase verbosity (can be used multiple times)
.SH SEE ALSO
http://opentrigger.com/
.SH BUGS
https://github.com/acolono/opentrigger-distributor/issues

.SH AUTHOR
Florian Fida
